language: cpp
dist: xenial
compiler: gcc

before_install:
  - chmod +x ./build.sh
  - chmod +x ./build.pro
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # C++11
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5 # C++11
  
script: 
  - ./build.sh
